prometheus.rules: |
   groups:
   - name: example-rules
     interval: 30s # defaults to global interval
     rules:
     - alert: "Node Down"
       expr: up{job="kubernetes-nodes"} == 0
       annotations:
         miqTarget: "ContainerNode"
         severity: "ERROR"
         url: "https://www.example.com/node_down_fixing_instructions"
         message: "Node {{$labels.instance}} is down"
     - alert: "Too Many Pods"
       expr: sum(kubelet_running_pod_count) > 15
       annotations:
         miqTarget: "ExtManagementSystem"  
         severity: "ERROR"
         url: "https://www.example.com/too_many_pods_fixing_instructions"
         message: "Too many running pods"
